from setuptools import setup, find_packages


setup(name="equibot",
      version="0.1",
      description="",
      author="",
      author_email="",
      license="",
      packages=find_packages(),
      install_requires=[
          "click",
          "matplotlib",
          "scipy",
          "tqdm",
          "opencv-python==4.9.0.80",
          "opencv-python-headless==4.9.0.80",
          "opencv-contrib-python==4.7.0.72",
          "hydra-core",
          "wandb",
          "chardet",
          "trimesh[all]",
          "natsort",
          "ffmpeg",
          "imageio[ffmpeg]",
          "ipykernel",
          "robosuite",
          "gtimer",
          "h5py",
          "scikit-video",
          "einops",
          "diffusers==0.24.0",
          "huggingface-hub==0.19.4",
          "gym==0.26.2",
          "pybullet==3.2.6",
          "protobuf==3.20.0"
      ])
