defaults:
  - base

env:
  env_class: nut_assembly_fixed
  num_eef: 1
  dof: 7
  eef_dim: 13
  args:
    num_eef: 1
    dof: 7
    max_episode_length: 300
    freq: 20
    randomize_rotation: true

training:
  batch_size: 512
  num_epochs: 2000
  lr: 4.8e-4
  eval_interval: 200
  save_interval: 50

wandb:
  entity: null
  project: dp
